"""Author a compact, texture-free Wii-style helmet in Mario HEAD bone space.

Native Mario's decoded head has X up, Y forward, Z across, with the old cap
reaching X=272, Y=-139..155, Z=-133..134. These are pre-GEO_SCALE units.
No ROM data is copied into this mesh. CAP/EMBLEM use editable player lights.
"""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1]
parts = {}

def triangle(part, a, b, c):
    u = [b[i]-a[i] for i in range(3)]
    v = [c[i]-a[i] for i in range(3)]
    n = [u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0]]
    length = math.sqrt(sum(x*x for x in n))
    if length < .001: return
    normal = [round(x*127/length) & 255 for x in n]
    parts.setdefault(part, []).extend((tuple(round(x) for x in p), normal) for p in (a,b,c))

def quad(part, a,b,c,d):
    triangle(part,a,b,c); triangle(part,a,c,d)

def dome(part, bottom, height, ry, rz, center_y=-12, rings=7, segments=24):
    def point(j,k):
        angle=2*math.pi*k/segments
        elevation=math.pi*.5*j/rings
        # Face opening rises above the eyebrows; sides/back cover the old cap.
        lip=55*max(0, math.cos(angle))**2
        return (bottom+height*math.sin(elevation)+lip*(1-math.sin(elevation)),
                center_y+ry*math.cos(elevation)*math.cos(angle),
                rz*math.cos(elevation)*math.sin(angle))
    for j in range(rings):
        for k in range(segments):
            quad(part,point(j,k),point(j,k+1),point(j+1,k+1),point(j+1,k))

def cylinder(part,x0,x1,radius,cy=0,cz=0,segments=16):
    for k in range(segments):
        a=2*math.pi*k/segments; b=2*math.pi*(k+1)/segments
        p=(x0,cy+radius*math.cos(a),cz+radius*math.sin(a))
        q=(x0,cy+radius*math.cos(b),cz+radius*math.sin(b))
        r=(x1,q[1],q[2]); s=(x1,p[1],p[2])
        quad(part,p,q,r,s)
        triangle(part,(x1,cy,cz),s,r)

dome('helmet',120,166,153,145)
cylinder('rotor_mount',281,318,14,-12)
# Side badges: round white backing and raised red M, one on each side.
for side in (-1,1):
    def badge_point(x,y,raised=1):
        z=145*math.sqrt(max(0,1-((x-120)/166)**2-((y+12)/153)**2))
        return (x,y,side*(z+raised))
    for k in range(24):
        a=2*math.pi*k/24; b=2*math.pi*(k+1)/24
        triangle('badge',badge_point(160,-12),badge_point(160+36*math.cos(a),-12+36*math.sin(a)),
                 badge_point(160+36*math.cos(b),-12+36*math.sin(b)))
    # Stylized M in side-plane coordinates (up=X, horizontal=Y).
    # Four non-overlapping strokes, avoiding concave fan triangulation.
    for pts in [((-23,-23),(-23,23),(-12,23),(-11,-23)),
                ((11,-23),(12,23),(23,23),(23,-23)),
                ((-12,23),(0,3),(0,-14),(-14,7)),
                ((0,3),(12,23),(14,7),(0,-14))]:
        quad('letter',*(badge_point(160+up,-12+horizontal,2) for horizontal,up in pts))

# Rotor is centered at its own origin, attached at X=318. Two broad rounded
# blades, slightly pitched and closed so they read correctly from below too.
for sign in (-1,1):
    plan=[(8,-12),(170,-27),(218,-17),(227,0),(216,17),(165,24),(8,12)]
    top=[(5+z*.08,sign*y,sign*z) for y,z in plan]
    bottom=[(-5+z*.08,sign*y,sign*z) for y,z in plan]
    for j in range(1,len(plan)-1):
        triangle('rotor',top[0],top[j],top[j+1])
        triangle('rotor',bottom[0],bottom[j+1],bottom[j])
    for j in range(len(plan)):
        k=(j+1)%len(plan)
        quad('rotor',top[j],bottom[j],bottom[k],top[k])
cylinder('rotor',-7,12,21)
parts['held_rotor']=[((p[0]+318,p[1]-12,p[2]),n) for p,n in parts['rotor']]

# Hammer helmet: rounded black crown, white rolled rim and circular ear guards.
dome('hammer_crown',120,160,155,147)
for k in range(32):
    a=2*math.pi*k/32; b=2*math.pi*(k+1)/32
    def rim(t,h):
        return (120+55*max(0,math.cos(t))**2+h,-12+157*math.cos(t),149*math.sin(t))
    quad('hammer_rim',rim(a,-5),rim(b,-5),rim(b,8),rim(a,8))
for side in (-1,1):
    for k in range(24):
        a=2*math.pi*k/24;b=2*math.pi*(k+1)/24
        triangle('hammer_rim',(131,-12,side*150),
                 (131+39*math.cos(a),-12+39*math.sin(a),side*151),
                 (131+39*math.cos(b),-12+39*math.sin(b),side*151))

lines=['// Generated by tools/generate-propeller-helmet.py; original procedural mesh.',
       '#include "game/player_palette.h"',
       'static const Lights1 vr_propeller_badge_light = gdSPDefLights1(100,100,100,255,255,255,40,40,40);',
       'static const Lights1 vr_hammer_helmet_light = gdSPDefLights1(12,12,15,42,42,48,40,40,40);']
for part,vertices in parts.items():
    lines.append(f'static const Vtx vr_propeller_{part}_vtx[] = {{')
    for pos,normal in vertices:
        lines.append('    {{{%d,%d,%d},0,{0,0},{%d,%d,%d,255}}},' % (*pos,*normal))
    lines.append('};')
    lines.append(f'static const Gfx vr_propeller_{part}_mesh[] = {{')
    for offset in range(0,len(vertices),30):
        count=min(30,len(vertices)-offset)
        lines.append(f'    gsSPVertex(vr_propeller_{part}_vtx + {offset}, {count}, 0),')
        for j in range(0,count,3): lines.append(f'    gsSP1Triangle({j},{j+1},{j+2},0),')
    lines.extend(['    gsSPEndDisplayList(),','};'])

def display(name,sequence):
    lines.extend([f'const Gfx {name}[] = {{','    gsDPPipeSync(),',
                  '    gsSPClearGeometryMode(G_TEXTURE_GEN | G_CULL_BOTH),',
                  '    gsSPSetGeometryMode(G_LIGHTING),',
                  '    gsSPTexture(0,0,0,G_TX_RENDERTILE,G_OFF),',
                  '    gsDPSetCombineMode(G_CC_SHADE, G_CC_SHADE),'])
    for mesh,color in sequence:
        if color=='BLACK':
            lines.extend(['    gsSPLight(&vr_hammer_helmet_light.l,1),','    gsSPLight(&vr_hammer_helmet_light.a,2),',f'    gsSPDisplayList(vr_propeller_{mesh}_mesh),'])
            continue
        lines.append('    gsSPLight(&vr_propeller_badge_light.l,1),' if color=='WHITE' else f'    gsSPCopyLightsPlayerPart({color}),')
        if color=='WHITE': lines.append('    gsSPLight(&vr_propeller_badge_light.a,2),')
        lines.append(f'    gsSPDisplayList(vr_propeller_{mesh}_mesh),')
    lines.extend(['    gsSPSetGeometryMode(G_CULL_BACK),','    gsSPEndDisplayList(),','};'])

display('vr_propeller_helmet_dl',[('helmet','CAP'),('badge','WHITE'),('letter','CAP'),('rotor_mount','EMBLEM')])
display('vr_propeller_rotor_dl',[('rotor','EMBLEM')])
display('vr_propeller_held_helmet_dl',[('helmet','CAP'),('badge','WHITE'),('letter','CAP'),('rotor_mount','EMBLEM'),('held_rotor','EMBLEM')])
display('vr_hammer_helmet_dl',[('hammer_crown','BLACK'),('hammer_rim','WHITE')])
out=ROOT/'actors/propeller_mushroom/helmet.inc.c'
out.write_text('\n'.join(lines)+'\n')
print(f'{sum(len(v)//3 for v in parts.values())} triangles -> {out}')

# Optional local mesh preview (not an in-game screenshot or shipped asset).
if '--preview' in __import__('sys').argv:
    from PIL import Image, ImageDraw
    canvas=Image.new('RGB',(1100,760),(28,32,42)); draw=ImageDraw.Draw(canvas)
    polygons=[]
    def project(p):
        x,y,z=p
        return (550+(z*.82-y*.57)*1.5,660-x*1.5-(y*.82+z*.57)*.4)
    for name,vertices in parts.items():
        color=(235,40,36) if name in ('helmet','letter') else (255,207,23)
        if name=='badge':color=(255,255,255)
        for j in range(0,len(vertices),3):
            tri=[vertices[j+k][0] for k in range(3)]
            if name=='rotor':tri=[(p[0]+318,p[1]-12,p[2]) for p in tri]
            normal=[n if n<128 else n-256 for n in vertices[j][1]]
            shade=.62+.38*abs((normal[0]*.7+normal[1]*.3+normal[2]*.4)/127)
            depth=sum(p[1]*.82+p[2]*.57+p[0]*.267 for p in tri)/3
            polygons.append((depth,tri,tuple(min(255,round(c*shade)) for c in color)))
    # Per-pixel depth, not painter ordering: inspect interpenetration accurately.
    pixels=canvas.load(); depth_buffer=[-float('inf')]*(1100*760)
    for _,tri,color in polygons:
        a,b,c=[project(p) for p in tri]
        depths=[p[1]*.82+p[2]*.57+p[0]*.267 for p in tri]
        denominator=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1])
        if abs(denominator)<.01:continue
        for y in range(max(0,math.floor(min(a[1],b[1],c[1]))),min(760,math.ceil(max(a[1],b[1],c[1])))):
            for x in range(max(0,math.floor(min(a[0],b[0],c[0]))),min(1100,math.ceil(max(a[0],b[0],c[0])))):
                u=((b[1]-c[1])*(x+.5-c[0])+(c[0]-b[0])*(y+.5-c[1]))/denominator
                v=((c[1]-a[1])*(x+.5-c[0])+(a[0]-c[0])*(y+.5-c[1]))/denominator
                w=1-u-v
                if min(u,v,w)<0:continue
                z=u*depths[0]+v*depths[1]+w*depths[2]
                index=y*1100+x
                if z>depth_buffer[index]:depth_buffer[index]=z;pixels[x,y]=color
    draw.text((24,24),'Propeller helmet - local mesh preview (not in-game)',fill='white')
    canvas.save(ROOT/'build/propeller-helmet-preview.png')
